labels:
  app: docker-gocd-server
  app-group: gocd
  container: gocd-server
  language: docker
  team: tooling

pipelines:
  bake:
    image: extensions/docker:stable
    action: build
    no-cache: true
    expand-variables: false
    container: ${ESTAFETTE_LABEL_CONTAINER}
    repositories:
    - travix

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:stable
        action: dive
        container: ${ESTAFETTE_LABEL_CONTAINER}
        repositories:
        - travix

      vulnerability-scan:
        image: extensions/docker:stable
        action: trivy
        container: ${ESTAFETTE_LABEL_CONTAINER}
        repositories:
        - travix

  push-to-docker-hub-branch:
    image: extensions/docker:stable
    action: push
    container: ${ESTAFETTE_LABEL_CONTAINER}
    repositories:
    - travix
    tags:
    - ${ESTAFETTE_GIT_BRANCH}
    when:
      status == 'succeeded' &&
      branch != 'master'

  push-to-docker-hub-latest:
    image: extensions/docker:stable
    action: push
    container: ${ESTAFETTE_LABEL_CONTAINER}
    repositories:
    - travix
    tags:
    - latest
    when:
      status == 'succeeded' &&
      branch == 'master'

  slack-notify:
    image: extensions/slack-build-status:stable
    workspace: travix
    channels:
    - '#swat-team'
    when:
      status == 'failed'